# Generated by Django 5.1.7 on 2025-03-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChargesEnseignement',
            fields=[
                ('id_charge', models.AutoField(primary_key=True, serialize=False)),
                ('palier', models.CharField(blank=True, db_column='PALIER', max_length=20, null=True)),
                ('specialite', models.CharField(blank=True, db_column='SPECIALITE', max_length=50, null=True)),
                ('semestre', models.CharField(blank=True, db_column='SEMESTRE', max_length=10, null=True)),
                ('section', models.CharField(blank=True, db_column='SECTION', max_length=10, null=True)),
                ('groupe', models.CharField(blank=True, db_column='Groupe', max_length=10, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=20, null=True)),
                ('intitulé_module', models.CharField(blank=True, db_column='Intitulé MODULE', max_length=100, null=True)),
                ('enseignant', models.IntegerField(blank=True, db_column='Enseignant', null=True)),
            ],
            options={
                'verbose_name': 'Charge d’enseignement',
                'verbose_name_plural': 'Charges d’enseignement',
                'db_table': 'charges_enseignement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enseignants',
            fields=[
                ('code_enseignant', models.CharField(db_column='Code Enseignant', max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='NOM', max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, db_column='PRENOM', max_length=50, null=True)),
                ('nom_jeune_fille', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, db_column='Genre', max_length=10, null=True)),
                ('etat', models.CharField(blank=True, db_column='Etat', max_length=30, null=True)),
                ('departement', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, db_column='GRADE', max_length=20, null=True)),
                ('email1', models.CharField(blank=True, max_length=100, null=True)),
                ('email2', models.CharField(blank=True, max_length=100, null=True)),
                ('tel1', models.CharField(blank=True, max_length=20, null=True)),
                ('tel2', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'enseignants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('palier', models.CharField(blank=True, db_column='PALIER', max_length=20, null=True)),
                ('specialite', models.CharField(blank=True, db_column='SPECIALITE', max_length=50, null=True)),
                ('semestre', models.CharField(blank=True, db_column='SEMESTRE', max_length=10, null=True)),
                ('intitulé_module', models.CharField(blank=True, db_column='Intitulé MODULE', max_length=100, null=True)),
                ('abv_module', models.CharField(db_column='Abv MODULE', max_length=20, primary_key=True, serialize=False)),
                ('coeff', models.DecimalField(blank=True, db_column='Coeff', decimal_places=2, max_digits=4, null=True)),
                ('crédit', models.DecimalField(blank=True, db_column='Crédit', decimal_places=2, max_digits=4, null=True)),
                ('unité', models.CharField(blank=True, db_column='Unité', max_length=10, null=True)),
                ('vhc', models.IntegerField(blank=True, db_column='VHC', null=True)),
                ('vhtd', models.IntegerField(blank=True, db_column='VHTD', null=True)),
                ('vhtp', models.IntegerField(blank=True, db_column='VHTP', null=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'db_table': 'formations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palier', models.CharField(blank=True, db_column='PALIER', max_length=20, null=True)),
                ('specialite', models.CharField(blank=True, db_column='SPECIALITE', max_length=50, null=True)),
                ('semestre', models.CharField(blank=True, db_column='SEMESTRE', max_length=10, null=True)),
                ('section', models.CharField(blank=True, db_column='SECTION', max_length=10, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('horaire', models.CharField(blank=True, db_column='Horaire', max_length=50, null=True)),
                ('salles', models.CharField(blank=True, db_column='Salles', max_length=100, null=True)),
                ('intitulé_module', models.CharField(blank=True, db_column='Intitulé MODULE', max_length=100, null=True)),
                ('surveillant', models.IntegerField(blank=True, db_column='Surveillant', null=True)),
                ('ordre', models.IntegerField(blank=True, db_column='Ordre', null=True)),
                ('nbrse', models.IntegerField(blank=True, db_column='NbrSE', null=True)),
                ('nbrss', models.IntegerField(blank=True, db_column='NbrSS', null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=100, null=True)),
            ],
            options={
                'db_table': 'surveillance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('nom_utilisateur', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('rang', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateurs',
                'managed': False,
            },
        ),
    ]
