# Generated by Django 5.1.7 on 2025-10-30 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklistBlacklistedtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blacklisted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'token_blacklist_blacklistedtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklistOutstandingtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('jti', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'token_blacklist_outstandingtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id_creneau', models.AutoField(primary_key=True, serialize=False)),
                ('date_creneau', models.DateField()),
                ('heure_creneau', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'creneau',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enseignants',
            fields=[
                ('Code_Enseignant', models.CharField(blank=True, db_column='Code Enseignant', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(blank=True, db_column='NOM', max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, db_column='PRENOM', max_length=50, null=True)),
                ('nom_jeune_fille', models.CharField(blank=True, db_column='Nom Jeune Fille', max_length=255, null=True)),
                ('genre', models.CharField(blank=True, db_column='Genre', max_length=10, null=True)),
                ('etat', models.CharField(blank=True, db_column='Etat', max_length=30, null=True)),
                ('departement', models.CharField(blank=True, db_column='Département', max_length=255, null=True)),
                ('grade', models.CharField(blank=True, db_column='GRADE', max_length=20, null=True)),
                ('diplome', models.CharField(blank=True, db_column='Diplôme', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=100, null=True)),
                ('email1', models.CharField(blank=True, db_column='EMAIL1', max_length=255, null=True)),
                ('email2', models.CharField(blank=True, db_column='EMAIL2', max_length=255, null=True)),
                ('tel1', models.CharField(blank=True, db_column='TEL1', max_length=50, null=True)),
                ('tel2', models.CharField(blank=True, db_column='TEL2', max_length=50, null=True)),
            ],
            options={
                'db_table': 'enseignants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(blank=True, db_column='Domaine', max_length=100, null=True)),
                ('filiere', models.CharField(blank=True, db_column='Filière', max_length=100, null=True)),
                ('niveau_cycle', models.CharField(blank=True, db_column='Niveau/Cycle', max_length=100, null=True)),
                ('specialites', models.CharField(blank=True, db_column='Spécialités', max_length=100, null=True)),
                ('nbr_sections', models.IntegerField(blank=True, db_column='Nbr Sections', null=True)),
                ('nbr_groupes', models.IntegerField(blank=True, db_column='Nbr groupes', null=True)),
                ('semestre', models.CharField(blank=True, db_column='Semestre', max_length=100, null=True)),
                ('modules', models.CharField(blank=True, db_column='Modules', max_length=255, null=True)),
            ],
            options={
                'db_table': 'formations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('nom_utilisateur', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('rang', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilisateurs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChargesEnseignement',
            fields=[
                ('id_charge', models.AutoField(primary_key=True, serialize=False)),
                ('palier', models.CharField(blank=True, db_column='PALIER', max_length=20, null=True)),
                ('specialite', models.CharField(blank=True, db_column='SPECIALITE', max_length=50, null=True)),
                ('semestre', models.CharField(blank=True, db_column='SEMESTRE', max_length=10, null=True)),
                ('section', models.CharField(blank=True, db_column='SECTION', max_length=10, null=True)),
                ('groupe', models.CharField(blank=True, db_column='Groupe', max_length=10, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=20, null=True)),
                ('intitule_module', models.CharField(blank=True, db_column='Intitulé MODULE', max_length=100, null=True)),
                ('abv_module', models.CharField(blank=True, db_column='Abv MODULE', max_length=20, null=True)),
                ('annee_universitaire', models.CharField(max_length=7)),
                ('Code_Enseignant_id', models.OneToOneField(blank=True, db_column='Code_Enseignant', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='link_db.enseignants')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='link_db.formations')),
            ],
            options={
                'db_table': 'charges_enseignement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id_planning', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=10)),
                ('nombre_surveillant', models.IntegerField()),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='link_db.formations')),
                ('id_creneau', models.ForeignKey(db_column='id_creneau', on_delete=django.db.models.deletion.DO_NOTHING, to='link_db.creneau')),
            ],
            options={
                'db_table': 'planning',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Surveillant',
            fields=[
                ('id_surveillance', models.AutoField(primary_key=True, serialize=False)),
                ('est_charge_cours', models.IntegerField(blank=True, null=True)),
                ('code_enseignant', models.ForeignKey(db_column='code_enseignant', on_delete=django.db.models.deletion.DO_NOTHING, to='link_db.enseignants')),
                ('id_planning', models.ForeignKey(db_column='id_planning', on_delete=django.db.models.deletion.DO_NOTHING, to='link_db.planning')),
            ],
            options={
                'db_table': 'surveillant',
                'managed': True,
            },
        ),
    ]
