# Generated by Django 5.1.7 on 2025-04-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_db', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.AlterModelOptions(
            name='chargesenseignement',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='enseignants',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='formations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='utilisateurs',
            options={'managed': False},
        ),
    ]
